version: '3.8'

services:
  inference-service:
    build:
      context: ./inference-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./inference-service:/app
    environment:
      - PYTHONUNBUFFERED=1
